### ISSUE TITLE
DEST_FINAL is not writable

### ISSUE THREAD

**Issue by Caledrith** [laur89/docker-seedbox-rclone-fetch-extract#3]
I apologize if there is something about docker I don't understand, but I attempted to build a docker compose yml to run this container. 

```
version: "2.1"
  services:
    seedbox-fetcher:
      container_name: seedbox-fetcher
      image: layr/seedbox-rclone-fetch-extract
      environment:
       - REMOTE=seedbox
       - SRC_DIR=/torrents/rtorrent
       - DEST_INITIAL=/path/to/initial
       - DEST_FINAL=/path/to/final
       - PUID=1000 
       - PGID=1000
    volumes:
     - /media:/data 
     - /path/to/config:/config 
 ``` (1000:1000 is my normal user on the vm)

When I locally use the config file (which is contained on my vm) to sync, it works. In the container logs, the container gives me this log essentially over and over

`crond: USER abc pid 1184 cmd sync.sh
sendmail: can't connect to remote host (127.0.0.1): Connection refused`

When I use `sudo docker exec -it --user abc seedbox-fetcher /bin/sh` to get into the container, I get the following error when I run ./sync.sh

`[sync-34] ERROR  DEST_FINAL /path/to/final] is not writable`

This seems insane to me as the /path/to/final permissions are `drwxrwxrwt   2 abc  abc    4096 Dec 23 08:23  Downloads` (I realize this is insecure, I just have been beating my head against the wall about this forever).

When I execute just `echo "$DEST_FINAL is $( [[ -w "$DEST_FINAL" ]] && echo "writable" || echo "not writable" )"`, I get that the folder is writable. Only within the script does it fail, and I've altered the script to export the condition that's giving this error in `common.sh`.

Is there something I'm missing?

**Comment by laur89** [comment]
Could you post the actual contents of the compose file? Current example shows no `volume` mapping for `/path/to/{initial,final}`

**Comment by Caledrith** [comment]
```
version: "2.1"
  services:
    seedbox-fetcher:
        container_name: seedbox-fetcher
        image: layr/seedbox-rclone-fetch-extract
        environment:
         - REMOTE=seedbox
         - SRC_DIR=/torrents/rtorrent
         - DEST_INITIAL=/data/rclone-tmp
         - DEST_FINAL=/data/Downloads
         - PUID=1000
         - PGID=1000
        volumes:
         - /media:/data 
         - /home/jmnemelka/.config/rclone:/config
```

/media on my vm is a mount of my NAS. `docker` is my vm name. As you can see, I've completely removed file restrictions from almost everything
![image](https://github.com/laur89/docker-seedbox-rclone-fetch-extract/assets/7317036/cfae1c9d-0685-45c6-babf-7a58d186a0b0)
1000 (the PUID/PGID in my compose) is that of my user.
![image](https://github.com/laur89/docker-seedbox-rclone-fetch-extract/assets/7317036/97bff110-f0a0-4b03-a596-e174a64a9295)
Screenshot of confirmed permissions inside container
![image](https://github.com/laur89/docker-seedbox-rclone-fetch-extract/assets/7317036/623755a8-616a-40e1-8b8b-75908199313d)
